[general]
[web]
listen = "0.0.0.0:4000"

[defaults]
keyfile="/home/scylla/.ssh/scylla"
connect-timeout=10
read-timeout=0 # Default
sudo-command = "sudo -i /bin/bash -c"
user=scylla
notifier = slack

[notifier "slack"]
path=./notifiers/slack
arg=foo
arg=changeme
arg=ops

[notifier "slack_edge"]
path=./notifiers/slack
arg=foo
arg=changeme
arg=ops
edge-trigger=true


[job "2fails"]
command = "if [[ $((RANDOM % 3)) == 0 ]]; then echo FAILED; exit 1; else echo OK; exit 0; fi"
schedule = cron */1 * * * *
description = Every 1 minutes
host = localhost
sudo = no
# fails-to-notify=2
notifier = slack
