#!/bin/bash

STATUS=${1}
JOB=${2}
RUN=${3}
ORG=${4}
TOKEN=${5}
CHANNEL=${6}
CURL=/opt/local/bin/curl
ICON=":green_heart:"

if [ $STATUS == "failed" ]; then
  ICON=":boom:"
fi

$CURL -XPOST "https://${ORG}.slack.com/services/hooks/incoming-webhook?token=${TOKEN}" -d "
{
  \"channel\": \"${CHANNEL}\",
  \"username\": \"SCYLLA\",
  \"icon_emoji\": \"${ICON}\",
  \"text\": \"Job ${JOB}.${RUN} status: ${STATUS}\"
}"



